global:
  scrape_interval: 15s
  evaluation_interval: 15s

  external_labels:
    monitor: "codelab-monitor"

scrape_configs:
  - job_name: prometheus

    static_configs:
      - targets: ["localhost:9090"]

  - job_name: docker
    static_configs:
      - targets: ["host.docker.internal:9323"]

  - job_name: my_metrics
    honor_timestamps: true
    track_timestamps_staleness: false
    metrics_path: /metrics
    scheme: http
    follow_redirects: true
    enable_http2: true
    static_configs:
      - targets: ["notification-manager:8888"]
