# kind-config.yaml
  kind: Cluster
  apiVersion: kind.x-k8s.io/v1alpha4
  nodes:
    - role: control-plane
      labels:
        custom-label: "control-plane"
     
      extraPortMappings:
        - containerPort: 80
          hostPort: 80
          protocol: TCP
        - containerPort: 443
          hostPort: 443
          protocol: TCP
        - containerPort: 30001
          hostPort: 30001
          protocol: TCP
        - containerPort: 30002
          hostPort: 30002
          protocol: TCP  

