FROM python:3.11.1

# Imposta il working directory all'interno del container
WORKDIR /Python/SLA

COPY ./SLA/requirements.txt .

# Installa le dipendenze necessarie
RUN pip install --no-cache-dir -r requirements.txt

# Copia il tuo codice nella directory di lavoro
COPY  ./SLA .


# Comando di avvio dell'applicazione al momento dell'esecuzione del container
CMD ["python", "sla_manager.py"]